name: ConverterApp Build Test

on:
  push:
    branches: [ "main" ]
 

jobs:
  build-test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Publish ConverterApp
      run: dotnet publish -o $GITHUB_WORKSPACE/bin/publish
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      